<?php
/**
 * @author Immanuel Klinkenberg <immanuel.klinkenberg@jtl-software.com>
 * @copyright 2010-2017 JTL-Software GmbH
 */
namespace jtl\Connector\MappingTables;

use Doctrine\DBAL\Schema\Table;
use Doctrine\DBAL\Types\Type;


class MappingTableStub extends AbstractMappingTable
{
    const COL_ID1 = 'id1';
    const COL_ID2 = 'id2';
    const COL_VAR = 'strg';

    const TYPE = 'yolo';
    const TABLE_NAME = 'mapping_table';

    /**
     * @return string
     */
    public function getName()
    {
        return self::TABLE_NAME;
    }


    public function defineEndpoint()
    {
        $this
            ->addEndpointColumn(self::COL_ID1, Type::INTEGER)
            ->addEndpointColumn(self::COL_ID2, Type::INTEGER)
            ->addEndpointColumn(self::COL_VAR, Type::STRING, [], false)
        ;
    }

    /**
     * @return string
     */
    public function getType()
    {
        return self::TYPE;
    }

    public function createTableSchema(Table $tableSchema)
    {
        parent::createTableSchema($tableSchema); // TODO: Change the autogenerated stub
    }

    public function explodeEndpoint($endpointId)
    {
        return parent::explodeEndpoint($endpointId); // TODO: Change the autogenerated stub
    }

    public function implodeEndpoint(array $data)
    {
        return parent::implodeEndpoint($data); // TODO: Change the autogenerated stub
    }

    public function createEndpointData(array $data)
    {
        return parent::createEndpointData($data); // TODO: Change the autogenerated stub
    }

    public function addEndpointColumn($name, $type, array $options = [], $primary = true)
    {
        return parent::addEndpointColumn($name, $type, $options, $primary); // TODO: Change the autogenerated stub
    }

    public function hasEndpointColumn($name)
    {
        return parent::hasEndpointColumn($name); // TODO: Change the autogenerated stub
    }

    public function getEndpointColumns()
    {
        return parent::getEndpointColumns(); // TODO: Change the autogenerated stub
    }


}